/*
 * Copyright (c) 2012-2017 Arne Schwabe
 * Distributed under the GNU GPL v2 with additional terms. For full terms see the file doc/LICENSE.txt
 */

apply plugin: 'com.android.application'

repositories {
    jcenter()
    maven { url "https://jitpack.io" }
    maven { url 'https://maven.google.com' }
}


android {
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }

    /*sourceSets {
        main {
            aidl.srcDirs = ['src/main/aidl']
        }
    }*/

    namespace 'com.roqos.openvpnlib.remote'

    dependencies {
        //implementation project(path: ':main', configuration: 'main') // or 'noovpn3Debug' based on what you need
    }

    buildFeatures {
        aidl = true
    }
}

